[package]
name = "wukkOS"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.9.1"
x86_64 = "0.14.10"
rlibc = "1.0"
multiboot2 = { version = "0.14.0", optional = true }
linked_list_allocator = { version = "0.9.0", optional = true }
[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[features]
default = ["f_multiboot2", "f_ll_alloc"]
f_multiboot2 = ["dep:multiboot2"]
f_ll_alloc = ["dep:linked_list_allocator"]