[package]
name = "wukkOS"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.9.1"
x86_64 = "0.14.10"
rlibc = "1.0"
[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]